# Generated by Django 6.1 on 2026-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
