# Generated by Django 6.1 on 2026-09-19 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_shortlistitem_alter_application_options_and_more'),
        ('jobs', '0002_savedsearch_remove_jobposting_skills_and_more'),
        ('profiles', '0002_company_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.seekerprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tailored_note',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='shortlistitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='shortlistitem',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='profiles.seekerprofile'),
        ),
        migrations.AddConstraint(
            model_name='shortlistitem',
            constraint=models.UniqueConstraint(fields=('seeker', 'job'), name='one_shortlist_entry_per_job'),
        ),
    ]
