# Generated by Django 6.1 on 2026-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('jobs', 'Job search'), ('candidates', 'Candidate search')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('alerts_on', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'saved searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
