# Generated by Django 6.1 on 2026-09-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_company_jobposting_level_and_more'),
        ('profiles', '0004_seekerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', 'latitude', 'longitude'], name='jobs_jobpos_status_11ddc2_idx'),
        ),
    ]
