# Generated by Django 6.1 on 2026-09-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applicant_and_more'),
        ('profiles', '0002_company_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
