# Generated by Django 5.2.17 on 2026-09-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
